### PR TITLE
adding routes, controllers and views

### PR DESCRIPTION
**Pull request by cmolinan**
# ACTIVITIES 

## Description
In this project, I have created all controllers and views for the Blog app, adding simple placeholders for views with plain HTML.

## Project requirements
- The app handles the URLs used in the wireframes:  
localhost:3000/
localhost:3000/users
localhost:3000/users/1
localhost:3000/users/1/posts
localhost:3000/users/1/posts/1

-  For each URL, I created:
    - A route
    - An action in the correct controller.
    - A view file.

-  View files include only placeholders written in plain HTML

-  I added code to handle **only** the 4 required URLs.

### CODE REVIEW

**Review by tresorsawasawa — COMMENTED** [review]
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @cmolinan  :wave: :wave: 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑 🛑

You have submitted a project with **wrong linters config**. Make sure you use the **[correct ones for this project](https://github.com/microverseinc/linters-config/tree/master/ror)** before requesting new review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

---
_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by cmolinan** [comment]
@tresorsawasawa Done !!

**Review by descholar-ceo — APPROVED** [review]
Hi @cmolinan 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 Implemented all requirements ✔️ 
👍🏽 The PR has linters installed with no errors ✔️ 
👍🏽 The PR is following the correct git flow ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by cmolinan** [comment]
@descholar-ceo Thanks for your review!

**Pull request merged**
